workflows:
  ios-no-codesign-build:
    name: Build iOS IPA (No Codesign)
    # This tells Codemagic to use a Mac machine
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build iOS (No Codesign)
        script: flutter build ios --profile --no-codesign

      - name: Package to IPA
        script: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r -X app.ipa Payload

    artifacts:
      - app.ipa
      - build/ios/iphoneos/**/*.dSYM # Optional: Good for crash reporting